### PR TITLE
live preview migration to virtual server updates

### PR DESCRIPTION
**Pull request by abose**
- chore: init port staticServer for live preview
- chore: staticServer to virtual server migration for live preview

## testing
1. All unit tests pass/fail(4) as before.
2. Manual sanity tests in phoenix live preview on save working as before.

### CODE REVIEW

**Comment by phoenixide** [comment]
## Thank You for making this pull request.

**Comment by phoenixide** [comment]
## Thank You for making this pull request.

**Comment by phoenixide** [comment]
## Thank You for making this pull request.

**Comment by abose** [comment]
The security hotspot reported by sonar is in unit tests that are not relevant anymore that will be removed in further PRs.

**Pull request merged**
