### PR TITLE
Update strings.js

### PR DESCRIPTION
**Pull request by ViktorOn**
Changes:
- Many translation fixes
- Bug fixes, typos and other shortcomings

### CODE REVIEW

**Comment by phoenixide** [comment]
### Error: Contributor Licence Agreement Signature Missing
Please sign the Contributor Licence Agreement by clicking the following link.
<p align="center"> <a href="https://phcode-dev.github.io/contributor-license-agreement/">Click here to sign the CLA</a></p>
### Error: Contributor Licence Agreement Signature Missing
The following commiter(s) has not signed the Contributor Licence Agreement:
ViktorOn
Please sign the Contributor Licence Agreement by clicking the following link. 
<p align="center"> <a href="https://phcode-dev.github.io/contributor-license-agreement/">Click here to sign the CLA</a></p>

**Comment by abose** [comment]
Thanks a lot for contributing to Phoenix :) @ViktorOn 
Please sign the CLA to merge these changes:  https://phcode-dev.github.io/contributor-license-agreement/

**Comment by phoenixide** [comment]
### Error: Contributor Licence Agreement Signature Missing
Please sign the Contributor Licence Agreement by clicking the following link.
<p align="center"> <a href="https://phcode-dev.github.io/contributor-license-agreement/">Click here to sign the CLA</a></p>
### Error: Contributor Licence Agreement Signature Missing
The following commiter(s) has not signed the Contributor Licence Agreement:
ViktorOn
Please sign the Contributor Licence Agreement by clicking the following link. 
<p align="center"> <a href="https://phcode-dev.github.io/contributor-license-agreement/">Click here to sign the CLA</a></p>

**Comment by ViktorOn** [comment]
> Thanks a lot for contributing to Phoenix :) @ViktorOn Please sign the CLA to merge these changes: https://phcode-dev.github.io/contributor-license-agreement/

Doesn't the license (AGPL-3.0) provide for the ability to change/distribute the code after editing?

**Comment by abose** [comment]
The CLA is different from the AGPL license. 

CLA means that you as the author grants right to Phoenix to use the code you contribute under the AGPL License. Without the CLA, we assume that we do not have your consent to mark the code you provided as AGPL.

**Comment by phoenixide** [comment]
### Error: Contributor Licence Agreement Signature Missing
Please sign the Contributor Licence Agreement by clicking the following link.
<p align="center"> <a href="https://phcode-dev.github.io/contributor-license-agreement/">Click here to sign the CLA</a></p>
### Error: Contributor Licence Agreement Signature Missing
The following commiter(s) has not signed the Contributor Licence Agreement:
ViktorOn
Please sign the Contributor Licence Agreement by clicking the following link. 
<p align="center"> <a href="https://phcode-dev.github.io/contributor-license-agreement/">Click here to sign the CLA</a></p>

**Comment by abose** [comment]
Hi @ViktorOn Got any time to look at the CLA? Waiting on it to merge.

**Comment by ViktorOn** [comment]
> Hi @ViktorOn Got any time to look at the CLA? Waiting on it to merge.

I have read this agreement, but I will not sign it. If you want, **here I grant you the right to make these changes to the code and use it under the [AGPLv3](https://github.com/phcode-dev/phoenix/blob/main/LICENSE) license**

**Comment by abose** [comment]
> > Hi @ViktorOn Got any time to look at the CLA? Waiting on it to merge.
> 
> I have read this agreement, but I will not sign it. If you want, **here I grant you the right to make these changes to the code and use it under the [AGPLv3](https://github.com/phcode-dev/phoenix/blob/main/LICENSE) license**

Hi @ViktorOn Thanks for the update.

 We copied the same terms from Adobe's CLA from brackets before. Are there any concerns about the CLA so that i can review the concerning terms? 

Almost all OSS projects have project specific CLAs, Attached other CLAs for reference:
https://www.apache.org/licenses/contributor-agreements.html
https://openjsf.org/about/the-openjs-foundation-cla/
https://github.com/brackets-cont/contributor-license-agreement

**Comment by abose** [comment]
Archiving PR due to inactivity.

**Pull request closed without merging**
