### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sumitwarrior7**
### What kind of change does this PR introduce?

- Bugfix - fixes issues- give issue github url/details here.
- Feature

### Tests done
- Describe unit tests done
- Describe integration tests done
- Describe manual tests done

### pull request guidelines:
* It's OK to have multiple small commits as you work on the PR - we will let GitHub automatically squash it before merging.
* If adding new feature:, Provide convincing reason to add this feature. Ideally you should open a suggestion issue first and have it greenlighted before working on it.
* If fixing a bug:Provide detailed description of the bug in the PR, or link to an issue that does.
* Provide screenshots or gifs of the changes whenever possible.

### CODE REVIEW

**Comment by Sumitwarrior7** [comment]
Earlier :
Screenshot from 2023-10-30 18-32-35

After:
Screenshot from 2023-10-30 18-32-56

**Comment by Sumitwarrior7** [comment]
Earlier:
Screenshot from 2023-10-30 18-39-16

After:
Screenshot from 2023-10-30 18-32-56

**Comment by Sumitwarrior7** [comment]
My issue is very small, but please merge my pr 
it will not affect your code very much i know
But for me even this small contribution matters a lot 😔

Its humble request🙏  from myside to the project maintainers of this project to merge this pr

**Comment by abose** [comment]
Hi @Sumitwarrior7 Thanks for contributing to phcod. 
This specific change cannot be merged as the sentence construction in the form is intentional. 

You may however raise any other change to fix typos or other changes to add features/functionality.

Any small contribution matters for us too, so feel free to raise further changes that fix typos or missing links or if you are a coder, feature requests or bug fixes.

**Pull request closed without merging**
