### PR TITLE
Update How-To-Add-Translations.md

### PR DESCRIPTION
**Pull request by abhishek213-alb**
Fixed typos and imrpoved readbility

### What kind of change does this PR introduce?

-
- Docs

### Does this PR introduce a breaking change?
- No

### CODE REVIEW

**Comment by phoenixide** [comment]
### Error: Contributor Licence Agreement Signature Missing
Please sign the Contributor Licence Agreement by clicking the following link.
<p align="center"> <a href="https://phcode-dev.github.io/contributor-license-agreement/">Click here to sign the CLA</a></p>
### Error: Contributor Licence Agreement Signature Missing
The following commiter(s) has not signed the Contributor Licence Agreement:
abhishek213-alb
Please sign the Contributor Licence Agreement by clicking the following link. 
<p align="center"> <a href="https://phcode-dev.github.io/contributor-license-agreement/">Click here to sign the CLA</a></p>

**Comment by abose** [comment]
@abhishek213-alb Thanks for contributing.
Please sign the CLA for merging.

**Comment by abhishek213-alb** [comment]
@abose Signed sir

**Comment by abose** [comment]
LGTM Merging.
Thanks for contributing to phcode @abhishek213-alb

**Pull request merged**
