### PR TITLE
optimise: new-project window for 720p screens 

### PR DESCRIPTION
**Pull request by mathewdennis1**
This pr enables horizontal alignment of new-project window at 100% scaling on 720 p screens.

current state:
Screenshot from 2022-06-24 01-14-38
with this pr:

Screenshot from 2022-06-24 00-55-30

Video preview::

https://user-images.githubusercontent.com/78793827/175388634-3cb39e19-0d32-4654-895a-e3f70981e53b.mp4

### CODE REVIEW

**Comment by phoenixide** [comment]
## Thank You for making this pull request.

**Comment by abose** [comment]
@mathewdennis1 thank you for raising this pull request. 
Please update this pr so that only code-editor.html page uses the changes responsive.css

**Comment by phoenixide** [comment]
## Thank You for making this pull request.

**Comment by phoenixide** [comment]
## Thank You for making this pull request.

**Comment by phoenixide** [comment]
## Thank You for making this pull request.

**Comment by mathewdennis1** [comment]
hi @abose ,it seems that the irregularity is not  from the pr..it can be seen in phcode.dev at 90% scaling on a 720p screen(image attached below)..
image

it is fixed now:
image

**Comment by abose** [comment]
LGTM. Thanks for the changes @mathewdennis1 

Verified that the new project dialogue is being rendered properly in resolutions ranging from 580px to 2300px width. Merging

**Pull request merged**
